stages:
 - release

publish_image:
  image: docker:latest
  services:
  - docker:dind
  stage: release
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker build -t kuylar/lighttube .
    - export IMAGE_ID=`docker images -q "kuylar/lighttube"`
    - docker tag $IMAGE_ID kuylar/lighttube:`date +%Y%m%d`
    - docker tag $IMAGE_ID kuylar/lighttube:latest
    - docker push kuylar/lighttube